version: '3'

services:
    nginx:
        image: nginx:1.22
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build: ./docker/php
        volumes:
            - ./src:/var/www/html